### ISSUE TITLE
Ability to use browser local time

### ISSUE THREAD

**Issue by jippi** [sergiitk/pagerbeauty#102]
**Is your feature request related to a problem? Please describe.**

Our on-call team is split across 5 time zones, but our PD schedule is timed in NYC time. It would be useful to show the UI in local time rather than NYC time for everyone consuming it.

**Describe the solution you'd like**
I would see US team members on-call time in Europe/Copenhagen (my computer time) instead of US/New Yrok

**Comment by sergiitk** [comment]
Thank you so much for bringing this use case. I think this is important.
I'm going to prioritize this feature.
