### ISSUE TITLE
User Timezones are not accounted for on display

### ISSUE THREAD

**Issue by warmfusion** [sergiitk/pagerbeauty#122]
**Describe the bug**
Start and End times are based on the timezone of the individual that is on-call and not the timezone of the viewer.

There is no indication of the timezone, and as such results in the displayed information being incorrect.

**To Reproduce**
Create two schedules, with users in different timezones;

Example given that generates screenshot below;
- UK User from Nov 29, 2019 at 10:00 to Dec 6, 2019 at 10:00 
- USA User from Nov 30, 2019 at 04:00 to Dec 3, 2019 at 00:00 

**Expected behavior**

Start/End times are shown localised to the viewer, not the assigned users timezone.

**Screenshots**

![image](https://user-images.githubusercontent.com/2294568/69984298-bb1bdb80-1530-11ea-8889-16caf154074d.png)

**Comment by sergiitk** [comment]
Duplicates #102.
