### ISSUE TITLE
PagerDuty Overrides do not work on PagerBeauty 

### ISSUE THREAD

**Issue by klivan** [sergiitk/pagerbeauty#37]
**Describe the bug**
If you create an override in PagerDuty Pagerbeauty will still show a regular rotation instead of an override.

**To Reproduce**
1. Create an override for any Schedule
2. Create PagerBeauty widget for this Schedule
3. User from the original Schedule is shown as currently oncall. =

**Expected behavior**
User from "Override" is shown as currently oncall.

**Comment by sergiitk** [comment]
Thanks for the report @klivan!

**Comment by sergiitk** [comment]
Just verified — it does work. What you have seen was most likely was a schedule update issue fixed in #29; released in [v0.0.8](https://github.com/sergiitk/pagerbeauty/releases/tag/v0.0.8).
