### ISSUE TITLE
Doesn't work with the PD v2 API?

### ISSUE THREAD

**Issue by seanlutner** [sergiitk/pagerbeauty#42]
**Describe the bug**
I'm trying to get this setup and the `/v1/schedules.html` URI in the docs throws a 404 when I'm logged into my PD organization. According to PD, the v1 API was decommissioned as of 10/19. Does this mean you need to add v2 support?

**Comment by sergiitk** [comment]
Hey @seanlutner. Pagerbeauty is using V2 API https://v2.developer.pagerduty.com
Do you need help setting it up?

**Comment by seanlutner** [comment]
I think I do need some help as the URL listed in the setup docs for the pagerduty schedules doesn't seem to exist for me.

**Comment by sergiitk** [comment]
Thank you for your feedback, @seanlutner! I'm going to write more docs this week with detailed setup instructions. I hope this will help. Also, feel free to DM me on [twitter](https://twitter.com/sergiitk) or leave your questions in [gitter/pagerbeauty](https://gitter.im/pagerbeauty/Lobby).

Meanwhile, take a look at [Generating a General Access REST API Key](https://support.pagerduty.com/docs/using-the-api#section-generating-a-general-access-rest-api-key) page in PagerDuty docs. Read-only access is sufficient. According to the docs, to generate the key, you need the following:

> You must be an admin or account owner within PagerDuty to access your API key. REST API access is only included on the Platform Team plan or higher — API access is not included on the Lite plan.

**Comment by sergiitk** [comment]
Hey @seanlutner. I've implemented app logging in the latest version 0.2.0. You can enable verbose mode by adding this to `.env` file: `PAGERBEAUTY_LOG_LEVEL=verbose`.
It should give you a better understanding of when the app's failing.

**Comment by seanlutner** [comment]
Hi @sergiitk. Thanks for the update. Unless I'm misunderstanding something about how the app works, I don't think the problem is with the app itself. The URL https://myorg.pagerduty.com/v1/schedules.html throws a 404 for me when I try to hit it. I run the container with the config including my API token and then try to hit the schedules URL. I'm on a standard plan PD wise.

**Comment by seanlutner** [comment]
I think I see what I've been missing all this time. The schedules list isn't from pagerduty, it's from the app. I'll test that out and post results.

**Comment by sergiitk** [comment]
Ah. https://myorg.pagerduty.com/v1/schedules.html is not where you'll find the schedules.
`/v1/schedules.html` is a PagerBeauty page. So, if you run the container locally, you'll find it on `http://localhost:8080/v1/schedules.html`.

**Comment by sergiitk** [comment]
Ah, thanks. Taking note to disambiguate it in docs.

**Comment by sergiitk** [comment]
A local container would only work, but it'll only be visible from your own laptop. Also, to embed in DataDog dashboards, you need to host it behind HTTPS.
I'd recommend running it on Heroku. I'm planning to set up a demo on Heroku and publish the example later this week.

**Comment by seanlutner** [comment]
Got it. All makes sense. I can expose it externally from my infrastructure. Thanks for your help. I'm going to close this out as I know what I need to do now.

**Comment by sergiitk** [comment]
Yes, that's the basic idea: to run it on your own infrastructure. There just wasn't a better way to make it work.
Let me know if you'll have a success setting PagerBeauty up!
