### ISSUE TITLE
CORs issue in Firefox

### ISSUE THREAD

**Issue by johntdyer** [sergiitk/pagerbeauty#93]
**Describe the bug**
I am getting CORS errors when trying to run the app

```
Access to XMLHttpRequest at 'https://xxxoncall.herokuapp.com/v1/schedules/P2MB6K8.html?access_token=xxxxxxxecb18b163&theme=grafana' from origin 'https://grafana-achm4.xxxxxx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

````

**To Reproduce**
1. Followed the docs
2. Save and see image
3. refresh and get error
4. Consul shows CORs errors

**Comment by sergiitk** [comment]
Thank you for the report!

**Comment by sergiitk** [comment]
@johntdyer I just tried to verify the bug. To reproduced domain missmatch I used Grafana on running localhost and [demo PagerBeauty on Heroku](https://pagerbeauty.herokuapp.com/v1/schedules/PJ1P5JQ.html). I tried Firefox 62 and 65 and it worked in browsers:
![image](https://user-images.githubusercontent.com/672669/54081105-f1dc0280-42cc-11e9-8a9b-708ed7e3311a.png)

I believe you might have missed the part with setting `method` to `iFrame`:
![image](https://user-images.githubusercontent.com/672669/54081104-e5f04080-42cc-11e9-9848-1241968173ac.png)

**Comment by sergiitk** [comment]
Please let me know if this helped!

**Comment by johntdyer** [comment]
Hello,

 So its still happening 

![image](https://user-images.githubusercontent.com/58234/54148741-23f37e80-440b-11e9-8be2-3a9d8cf31318.png)

and here

![image](https://user-images.githubusercontent.com/58234/54148674-045c5600-440b-11e9-8f1a-37223b50b3cd.png)

When I build the panel it appears to work but then I refresh the dashboard and that is when it fails.... 

The config for the panel is

![image](https://user-images.githubusercontent.com/58234/54149193-ffe46d00-440b-11e9-8e11-af0af469167f.png)

**Comment by sergiitk** [comment]
Hmmm. That's strange.
I tried to reproduce this, but couldn't. Looking at the Request Error you posted, it does say `method: IFRAME`.

What firefox version are you using? Could you please also check if Chrome behave the same on your setup?

**Comment by sergiitk** [comment]
Ok, I even tried graphana running behind SSL. Still works fine:
![image](https://user-images.githubusercontent.com/672669/54330974-42659f80-45ee-11e9-97d6-c938ba238c89.png)

**Comment by sergiitk** [comment]
Also, try applyin "Image in IFrame load an image in an iframe " example and see if it works:
![image](https://user-images.githubusercontent.com/672669/54331224-6675b080-45ef-11e9-96d7-8c9675595d89.png)

**Comment by sergiitk** [comment]
Closed due to inactivity.
